version: "3.8"

services:
  react-challenge-app-backend:
    container_name: enrico-challenge-app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  react-challenge-app-frontend:
    container_name: enrico-challenge-app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      HOST: 0.0.0.0
      REACT_APP_API_ENDPOINT: "react-challenge-app-backend:3000"
    depends_on:
      - react-challenge-app-backend

  react-challenge-app-e2e:
    container_name: enrico-challenge-app-e2e
    build:
      context: ./e2e
      dockerfile: Dockerfile
    depends_on:
      - react-challenge-app-frontend
    network_mode: host
    volumes:
      - type: bind
        source: "./e2e/cypress/report"
        target: /usr/src/app/cypress/report
        volume:
          nocopy: true


